name: CI
on:
  pull_request_review:
    types:
      - submitted
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: Reject if not approved
        if: |
          github.event_name == 'pull_request_review'
          && github.event.review.state != 'approved'
        run: |
        echo github.event.review.state
        exit 1
      - uses: actions/checkout@v3
      # test