name: MyFancyWorkflow
on:
  workflow_dispatch:
  pull_request_review:
    types:
      - submitted
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  MyFancyJob:
    if: |
      # run after pr approval
      (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
      # run manually from github ci 
      || github.event_name == 'workflow_dispatch'
      # run by magic comment
      || github.event.review.body == 'trigger ci'
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo github.event_name = ${{ github.event_name }}
          echo github.event.review.state = ${{ github.event.review.state }}
          echo github.event.review.body = ${{ github.event.review.body }}
          exit 1
      - uses: actions/checkout@v3
      # test5